### ISSUE TITLE
segmentation fault 

### ISSUE THREAD

**Issue by spinGreekGod** [numerai/example-scripts#106]
Trying to compile `example_model.py`, but I am getting this error. I even tried running it with `sudo` but it didn't work. Any help would be nice
<img width="527" alt="Screen Shot 2021-12-12 at 7 32 46 PM" src="https://user-images.githubusercontent.com/49564726/145736224-8458ed73-3be9-45b8-89bf-686551c0278f.png">
.

**Comment by ndharasz** [comment]
Hi! If you're still experiencing this issue, some things that might help us debug would be:
- System specs
- Environment (python/conda versions, packages installed)

If you've solved the problem, feel free to submit a PR or reply in this thread with your solution so others can use the same solution.
